steps:
  - name: "CI {{matrix.arch}} -- {{matrix.os}}"
    matrix:
      setup:
        arch:
          - x86_64
          - arm64
        os:
          - linux
          - darwin
        bazel:
          - 5.2.0
    agents:
      queue: "juliaecosystem"
    commands: |
      uname -a
      uname -m
      mkdir -p .local/bin
      export PATH="`pwd`/.local/bin:$PATH"
      echo "openssl md5 | cut -d' ' -f2" > .local/bin/md5
      chmod +x .local/bin/md5
      PATH="`pwd`/.local/bin:$PATH" which md5

      # curl -fLO "https://github.com/bazelbuild/bazel/releases/download/{{matrix.bazel}}/bazel-{{matrix.bazel}}-installer-{{matrix.os}}-{{matrix.arch}}.sh"
      # bash bazel*.sh --prefix=`pwd`/.local
      # rm bazel*.sh
      if [ "$(uname)" == "Darwin" ]; then
        wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-MacOSX-{{matrix.arch}}.sh
      elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then      
	    wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Linux-{{matrix.arch}}.sh
      fi
      chmod +x Miniconda*.sh
      PATH="`pwd`/.local/bin:$PATH" ./Miniconda*.sh -b -p `pwd`/conda
      rm Miniconda*.sh
      `pwd`/conda/bin/conda activate
      `pwd`/conda/bin/conda install -c conda-forge bazel conda
      python -m ensurepip --upgrade
      python -m pip install --user numpy wheel
      bazel build :enzyme_jax
      cp bazel-bin/*.whl .
    artifact_paths:
      - "*.whl"

    timeout_in_minutes: 120
