steps:
  - name: "CI {{matrix.arch}} -- {{matrix.os}}"
    matrix:
      setup:
        arch:
          - x86_64
          - arm64
        os:
          - linux
          - darwin
          - windows
    agents:
      queue: "juliaecosystem"
    commands: |
      export PATH="$PATH:/sbin"
      wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-MacOSX-{{matrix.arch}}.sh
      bash *.sh -b -p miniconda
      ./miniconda/bin/activate
      python -m ensurepip --upgrade
      python -m pip install --user numpy wheel
      export BAZEL_VERSION=5.2.0
      curl -fLO "https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-{{matrix.os}}-{{matrix.arch}}.sh"
      chmod +x "bazel-$BAZEL_VERSION-installer-darwin-x86_64.sh"
      ./bazel-$BAZEL_VERSION-installer*.sh --user
      export PATH="PATH:HOME/bin"
      bazel build :enzyme_jax
      cp bazel-bin/*.whl .
    artifact_paths:
      - "*.whl"

    timeout_in_minutes: 120
