steps:
  - name: "CI {{matrix.arch}} -- {{matrix.os}}"
    matrix:
      setup:
        arch:
          - x86_64
          - arm64
        os:
          - linux
          - darwin
          - windows
    agents:
      queue: "juliaecosystem"
    commands: |
      python -m ensurepip --upgrade
      python -m pip install --user numpy
      bazel build :enzyme_jax
      cp bazel-bin/*.whl .
    artifact_paths:
      - "*.whl"

    timeout_in_minutes: 120
