steps:
  - name: "CI {{matrix.arch}} -- {{matrix.os}}"
    matrix:
      setup:
        arch:
          - x86_64
          - arm64
        os:
          - linux
          - darwin
          - windows
    agents:
      queue: "juliaecosystem"
    commands: |
      mkdir .local
      export BAZEL_VERSION=5.2.0
      curl -fLO "https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-{{matrix.os}}-{{matrix.arch}}.sh"
      bash bazel*.sh --prefix=`pwd`/.local
      export PATH="`pwd`/.local:$PATH"
      # python -m ensurepip --upgrade
      # python -m pip install --user numpy wheel
      bazel build :enzyme_jax
      cp bazel-bin/*.whl .
    artifact_paths:
      - "*.whl"

    timeout_in_minutes: 120
