steps:
  - name: "CI {{matrix.arch}} -- {{matrix.os}}"
    matrix:
      setup:
        arch:
          - aarch64
          - x86_64
        os:
          - linux
          - macos
          - windows
    agents:
      queue: "juliaecosystem"
      os: "{{matrix.os}}"
      arch: "{{matrix.arch}}"
    commands: |
      uname -a
      uname -m
      mkdir -p .local/bin
      export PATH="`pwd`/.local/bin:$PATH"
      echo "openssl md5 | cut -d' ' -f2" > .local/bin/md5
      chmod +x .local/bin/md5
      PATH="`pwd`/.local/bin:$PATH" which md5

      if [ "$(uname)" == "Darwin" ]; then
        curl -fLO https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-MacOSX-{{matrix.arch}}.sh
        chmod +x Miniconda*.sh
        PATH="`pwd`/.local/bin:$PATH" ./Miniconda*.sh -b -p `pwd`/conda
        rm Miniconda*.sh
      elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then      
        wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Linux-{{matrix.arch}}.sh
        chmod +x Miniconda*.sh
        PATH="`pwd`/.local/bin:$PATH" ./Miniconda*.sh -b -p `pwd`/conda
        rm Miniconda*.sh
      else
        wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Windows-{{matrix.arch}}.exe
        start /wait "" Miniconda3*.exe /InstallationType=JustMe /RegisterPython=0 /S /D=`pwd`/conda
        rm Miniconda*.exe
      fi
      `pwd`/conda/bin/conda init --all
      `pwd`/conda/bin/conda activate
      `pwd`/conda/bin/conda install -c conda-forge bazel conda
      python -m ensurepip --upgrade
      python -m pip install --user numpy wheel
      bazel build :enzyme_jax
      cp bazel-bin/*.whl .
    artifact_paths:
      - "*.whl"

    timeout_in_minutes: 120
