steps:
  - label: "CI {{matrix.arch}} -- {{matrix.os}}"
    matrix:
      setup:
        arch:
          - "x86_64"
          - "arm"
        os:
          - "linux"
          - "macOS"
          - "windows"
    agents:
      queue: "juliaecosystem"
      arch: {{matrix.arch}}
      os: {{matrix.os}}
    commands: |
      python3 -m pip install --user numpy
      bash patches/apply.sh
      bazel build :enzyme_jax
      cp bazel-bin/*.whl .
    artifact_paths:
      - "*.whl"

    timeout_in_minutes: 120
